FROM apontej/rver:4.0.0

# Based on https://github.com/rocker-org/rocker-versioned/blob/master/tidyverse/3.6.3.Dockerfile
# and https://github.com/rocker-org/rocker-versioned/blob/master/verse/3.6.3.Dockerfile

ARG CTAN_REPO=${CTAN_REPO:-https://www.texlive.info/tlnet-archive/2020/06/02/tlnet}
ENV CTAN_REPO=${CTAN_REPO}

ENV PATH=$PATH:/opt/TinyTeX/bin/x86_64-linux/

## Add LaTeX, rticles and bookdown support
RUN apt-get update -qq \ 
  && apt-get -y --no-install-recommends install \
  wget \
  libxml2-dev \
  libcairo2-dev \
  libsqlite-dev \
  libmariadbd-dev \
  libmariadbclient-dev \
  libpq-dev \
  libssh2-1-dev \
  unixodbc-dev \
  libsasl2-dev \
  curl \
  default-jdk \
  fonts-roboto \
  ghostscript \
  less \ 
  libbz2-dev \
  libicu-dev \
  liblzma-dev \
  libhunspell-dev \
  libjpeg-dev \
  libmagick++-dev \
  libopenmpi-dev \
  librdf0-dev \
  libtiff-dev \
  libv8-dev \
  libzmq3-dev \
  libgdal-dev \
  libproj-dev \
  libpcre2-dev \
  qpdf \
  ssh \
  texinfo \
  vim \  
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/ \
  && install2.r --error \
    --deps TRUE \
    tidyverse \
    dplyr \
    devtools \
    formatR \
    remotes \
    selectr \
    caTools \
    BiocManager \
  && wget "https://travis-bin.yihui.name/texlive-local.deb" \
  && dpkg -i texlive-local.deb \
  && rm texlive-local.deb \
  ## Use tinytex for LaTeX installation
  && install2.r --error tinytex \
  ## Admin-based install of TinyTeX:
  && wget -qO- \
    "https://github.com/yihui/tinytex/raw/master/tools/install-unx.sh" | \
    sh -s - --admin --no-path \
  && mv ~/.TinyTeX /opt/TinyTeX \
  && if /opt/TinyTeX/bin/*/tex -v | grep -q 'TeX Live 2018'; then \
      ## Patch the Perl modules in the frozen TeX Live 2018 snapshot with the newer
      ## version available for the installer in tlnet/tlpkg/TeXLive, to include the
      ## fix described in https://github.com/yihui/tinytex/issues/77#issuecomment-466584510
      ## as discussed in https://www.preining.info/blog/2019/09/tex-services-at-texlive-info/#comments
      wget -P /tmp/ ${CTAN_REPO}/install-tl-unx.tar.gz \
      && tar -xzf /tmp/install-tl-unx.tar.gz -C /tmp/ \
      && cp -Tr /tmp/install-tl-*/tlpkg/TeXLive /opt/TinyTeX/tlpkg/TeXLive \
      && rm -r /tmp/install-tl-*; \
    fi \
  && /opt/TinyTeX/bin/*/tlmgr path add \
  && tlmgr install ae inconsolata listings metafont mfware parskip pdfcrop tex \
  && tlmgr path add \
  && Rscript -e "tinytex::r_texmf()" \
  && chown -R root:staff /opt/TinyTeX \
  && chmod -R g+w /opt/TinyTeX \
  && chmod -R g+wx /opt/TinyTeX/bin \
  && echo "PATH=${PATH}" >> /usr/local/lib/R/etc/Renviron \
  && install2.r --error PKI \
  ## And some nice R packages for publishing-related stuff
  && R CMD javareconf \
  && install2.r --error --deps TRUE \
    bookdown rticles rmdshower rJava \
  && install2.r --error --deps TRUE --skipinstalled TRUE \
   && abc \
   && abc.data \
   && abind \
   && acepack \
   && acss.data \
   && actuar \
   && ada \
   && additivityTests \
   && ade4 \
   && adegenet \
   && adegraphics \
   && adehabitatHR \
   && adehabitatLT \
   && adehabitatMA \
   && adephylo \
   && adfExplorer \
   && ADGofTest \
   && ahaz \
   && airGR \
   && akima \
   && alabama \
   && AlgDesign \
   && analogue \
   && animation \
   && antaresProcessing \
   && antaresRead \
   && aod \
   && ape \
   && aqp \
   && archetypes \
   && archivist \
   && arm \
   && aroma.apd \
   && arsenal \
   && arules \
   && arulesViz \
   && ash \
   && askpass \
   && assertive \
   && assertive.base \
   && assertive.code \
   && assertive.data \
   && assertive.data.uk \
   && assertive.data.us \
   && assertive.datetimes \
   && assertive.files \
   && assertive.matrices \
   && assertive.models \
   && assertive.numbers \
   && assertive.properties \
   && assertive.reflection \
   && assertive.sets \
   && assertive.strings \
   && assertive.types \
   && assertthat \
   && AUC \
   && audio \
   && available \
   && aws.s3 \
   && aws.signature \
   && backports \
   && baRcodeR \
   && base64enc \
   && bayesm \
   && bayesplot \
   && bayestestR \
   && BB \
   && Benchmarking \
   && benchmarkme \
   && benchmarkmeData \
   && betareg \
   && BH \
   && bibtex \
   && biclust \
   && biglm \
   && bigmemory \
   && bigmemory.sri \
   && bindr \
   && bindrcpp \
   && binom \
   && bio3d \
   && Biobase \
   && BiocManager \
   && biogram \
   && BioInstaller \
   && bit \
   && bit64 \
   && bitops \
   && blm \
   && blme \
   && blob \
   && bmp \
   && bold \
   && bookdown \
   && boot \
   && brew \
   && brglm \
   && broom \
   && brranching \
   && bsplus \
   && btb \
   && Cairo \
   && callr \
   && candisc \
   && car \
   && carData \
   && caret \
   && caTools \
   && cellranger \
   && checkmate \
   && chron \
   && circlize \
   && CircStats \
   && circular \
   && citr \
   && class \
   && classInt \
   && cli \
   && clipr \
   && clisymbols \
   && clue \
   && cluster \
   && clusterGeneration \
   && coda \
   && codetools \
   && coin \
   && colorRamps \
   && colorspace \
   && colourpicker \
   && colourvalues \
   && combinat \
   && commonmark \
   && compare \
   && compareDF \
   && complexplus \
   && Compositional \
   && compositions \
   && CompQuadForm \
   && conditionz \
   && config \
   && configr \
   && copula \
   && CORElearn \
   && corrplot \
   && countrycode \
   && covr \
   && cowplot \
   && cranlogs \
   && crayon \
   && crosstalk \
   && crul \
   && cubature \
   && curl \
   && CVST \
   && DAAG \
   && data.table \
   && data.tree \
   && dataMaid \
   && dataMeta \
   && DBI \
   && dbplyr \
   && dbscan \
   && ddalpha \
   && debugme \
   && deldir \
   && dendextend \
   && densratio \
   && DEoptimR \
   && depth \
   && Deriv \
   && desc \
   && DescTools \
   && devtools \
   && DiagrammeR \
   && dichromat \
   && digest \
   && DirichletReg \
   && discretization \
   && dismo \
   && distr \
   && distrDoc \
   && distrEllipse \
   && distrEx \
   && distrMod \
   && distrRmetrics \
   && distrSim \
   && distrTeach \
   && distrTEst \
   && doMC \
   && doParallel \
   && doSNOW \
   && dotCall64 \
   && downloader \
   && dplyr \
   && drgee \
   && DRR \
   && DT \
   && dummies \
   && dygraphs \
   && dynamicTreeCut \
   && e1071 \
   && EbayesThresh \
   && effects \
   && effectsize \
   && eha \
   && elasticnet \
   && ellipse \
   && ellipsis \
   && emmeans \
   && emplik \
   && emulator \
   && energy \
   && entropy \
   && EnvStats \
   && erer \
   && estimability \
   && etm \
   && evaluate \
   && evd \
   && expint \
   && expm \
   && extraDistr \
   && extrafont \
   && extrafontdb \
   && fansi \
   && faraway \
   && farver \
   && fasterize \
   && fastICA \
   && fastmap \
   && fastmatch \
   && fBasics \
   && fda \
   && fftwtools \
   && fGarch \
   && fgui \
   && fields \
   && filehash \
   && filelock \
   && filematrix \
   && fit.models \
   && fitdistrplus \
   && flexclust \
   && flexmix \
   && flock \
   && fmsb \
   && FNN \
   && forcats \
   && foreach \
   && forecast \
   && formatR \
   && formattable \
   && Formula \
   && fracdiff \
   && fractal \
   && fractaldim \
   && fs \
   && functional \
   && furrr \
   && futile.logger \
   && futile.options \
   && future \
   && future.apply \
   && FuzzyNumbers \
   && gamlss \
   && gamlss.data \
   && gamlss.dist \
   && gbRd \
   && gclus \
   && gdata \
   && GDINA \
   && gdtools \
   && genalg \
   && GenBinomApps \
   && gender \
   && generics \
   && genetics \
   && geojson \
   && geojsonio \
   && geojsonsf \
   && geometry \
   && geoR \
   && geosphere \
   && getopt \
   && getPass \
   && GGally \
   && ggalt \
   && ggdendro \
   && ggedit \
   && ggeffects \
   && ggExtra \
   && ggforce \
   && ggformula \
   && ggfortify \
   && ggmap \
   && ggmcmc \
   && ggplot2 \
   && ggpubr \
   && ggrepel \
   && ggridges \
   && ggsci \
   && ggsignif \
   && ggsn \
   && ggspatial \
   && ggstance \
   && ggtern \
   && ggThemeAssist \
   && ggthemes \
   && ggvis \
   && gh \
   && GISTools \
   && git2r \
   && glm2 \
   && glmmTMB \
   && glmnet \
   && GlobalOptions \
   && globals \
   && glue \
   && gmodels \
   && gmp \
   && goftest \
   && googlePolylines \
   && gower \
   && gpclib \
   && gplots \
   && gridBase \
   && gridExtra \
   && gsl \
   && gss \
   && gstat \
   && gsubfn \
   && gtable \
   && gtools \
   && gWidgets \
   && haven \
   && heplots \
   && here \
   && hexbin \
   && highr \
   && HKprocess \
   && Hmisc \
   && hms \
   && htmlTable \
   && htmltools \
   && htmlwidgets \
   && httpcode \
   && httpuv \
   && httr \
   && hunspell \
   && ICGE \
   && ifultools \
   && igraph \
   && imager \
   && influenceR \
   && ini \
   && inline \
   && insight \
   && intervals \
   && introgress \
   && iotools \
   && ipred \
   && IRdisplay \
   && IRkernel \
   && Iso \
   && isoband \
   && ISOcodes \
   && ISwR \
   && iterators \
   && janeaustenr \
   && janitor \
   && jomo \
   && jpeg \
   && jqr \
   && jsonify \
   && jsonlite \
   && kableExtra \
   && kernelFactory \
   && kernlab \
   && KernSmooth \
   && keyring \
   && klaR \
   && kmer \
   && knitr \
   && labeling \
   && labelled \
   && lambda.r \
   && lars \
   && later \
   && latex2exp \
   && lattice \
   && latticeExtra \
   && lava \
   && lazyeval \
   && ldbounds \
   && leafem \
   && leaflet \
   && leaflet.minicharts \
   && leaflet.providers \
   && leafletR \
   && leafsync \
   && leaps \
   && LearnBayes \
   && lhs \
   && libcoin \
   && lifecycle \
   && limSolve \
   && linprog \
   && lisp \
   && listenv \
   && listviewer \
   && liteq \
   && lme4 \
   && lmerTest \
   && lmtest \
   && locfit \
   && logistf \
   && loo \
   && lpSolve \
   && lpSolveAPI \
   && ltsa \
   && lubridate \
   && lwgeom \
   && magic \
   && magick \
   && magrittr \
   && mailR \
   && manipulate \
   && manipulateWidget \
   && mapdeck \
   && mapproj \
   && maps \
   && maptools \
   && markdown \
   && MASS \
   && Matrix \
   && matrixcalc \
   && MatrixModels \
   && matrixStats \
   && maxLik \
   && mc2d \
   && mcmc \
   && MCMCpack \
   && MCPAN \
   && mda \
   && memoise \
   && memuse \
   && merTools \
   && meta \
   && metafor \
   && mfp \
   && mgcv \
   && MHadaptive \
   && mhsmm \
   && mice \
   && microbenchmark \
   && mime \
   && miniUI \
   && minpack.lm \
   && minqa \
   && miscF \
   && miscTools \
   && mitml \
   && mitools \
   && mixtools \
   && mixture \
   && ModelMetrics \
   && modelr \
   && modeltools \
   && modules \
   && moments \
   && mosaic \
   && mosaicCore \
   && mosaicData \
   && MplusAutomation \
   && mpoly \
   && mratios \
   && msm \
   && multcomp \
   && multicool \
   && munsell \
   && mvtnorm \
   && nabor \
   && natserv \
   && ncdf4 \
   && neldermead \
   && nleqslv \
   && nlme \
   && nloptr \
   && NLP \
   && NMF \
   && nnet \
   && nnls \
   && nortest \
   && np \
   && nparcomp \
   && numDeriv \
   && nycflights13 \
   && odbc \
   && OECD \
   && officer \
   && openNLP \
   && openNLPdata \
   && openssl \
   && openxlsx \
   && optimbase \
   && optimsimplex \
   && optparse \
   && ordinal \
   && orthopolynom \
   && overlap \
   && pacman \
   && padr \
   && pan \
   && pander \
   && parameters \
   && parsedate \
   && partitions \
   && pbapply \
   && pbdZMQ \
   && pbkrtest \
   && pcaPP \
   && pdist \
   && pegas \
   && penalized \
   && performance \
   && permute \
   && phangorn \
   && phonTools \
   && phylobase \
   && phylocomr \
   && phylogram \
   && PhysicalActivity \
   && phytools \
   && pillar \
   && pinfsc50 \
   && pingr \
   && pipeR \
   && pixmap \
   && pkgbuild \
   && pkgconfig \
   && pkgload \
   && pkgmaker \
   && plogr \
   && plotKML \
   && plotly \
   && plotrix \
   && pls \
   && plumber \
   && plyr \
   && png \
   && polspline \
   && polyclip \
   && polynom \
   && pool \
   && poweRlaw \
   && powerplus \
   && pracma \
   && praise \
   && prediction \
   && prettymapr \
   && prettyunits \
   && princurve \
   && pROC \
   && processx \
   && prodlim \
   && profileModel \
   && profvis \
   && progress \
   && proj4 \
   && promises \
   && proto \
   && protolite \
   && ProTrackR \
   && pryr \
   && ps \
   && pscl \
   && pspline \
   && psych \
   && psychotools \
   && purrr \
   && pwr \
   && qap \
   && qdap \
   && qdapDictionaries \
   && qdapRegex \
   && qdapTools \
   && qrcode \
   && quadprog \
   && quantmod \
   && quantreg \
   && questionr \
   && QUIC \
   && R.cache \
   && R.devices \
   && R.filesets \
   && R.huge \
   && R.matlab \
   && R.methodsS3 \
   && R.oo \
   && R.rsp \
   && R.utils \
   && R2HTML \
   && R2jags \
   && R2WinBUGS \
   && R6 \
   && rAmCharts \
   && RandomFields \
   && RandomFieldsUtils \
   && randomForest \
   && randtoolbox \
   && RandVar \
   && ranger \
   && RANN \
   && RApiDatetime \
   && rapidjsonr \
   && rappdirs \
   && rapportools \
   && rARPACK \
   && raster \
   && rbtt \
   && rcmdcheck \
   && RColorBrewer \
   && Rcpp \
   && RcppArmadillo \
   && RcppEigen \
   && RcppGSL \
   && RcppParallel \
   && RcppProgress \
   && RcppRoll \
   && RcppTOML \
   && RcppZiggurat \
   && RCurl \
   && rdhs \
   && Rdpack \
   && readbitmap \
   && readr \
   && readstata13 \
   && readxl \
   && recipes \
   && RefManageR \
   && registry \
   && relations \
   && rematch \
   && rematch2 \
   && remedy \
   && remotes \
   && rentrez \
   && repr \
   && reprex \
   && reshape \
   && reshape2 \
   && reticulate \
   && rex \
   && Rfast \
   && Rfast2 \
   && rgdal \
   && rgenoud \
   && rgeos \
   && rgexf \
   && rgl \
   && Rglpk \
   && RgoogleMaps \
   && rio \
   && ritis \
   && rjags \
   && rJava \
   && rjson \
   && RJSONIO \
   && rlang \
   && rlecuyer \
   && rlist \
   && rmarkdown \
   && Rmisc \
   && rms \
   && RMySQL \
   && rncl \
   && RNeXML \
   && rngtools \
   && rngWELL \
   && robust \
   && robustbase \
   && ROCR \
   && RODBCDBI \
   && Rook \
   && rootSolve \
   && rosm \
   && rotl \
   && roxygen2 \
   && rpart \
   && rpart.plot \
   && rpicosat \
   && RPostgres \
   && rprojroot \
   && rptR \
   && rrcov \
   && rredlist \
   && rriskDistributions \
   && RSAGA \
   && rsample \
   && rsdmx \
   && Rsolnp \
   && RSpectra \
   && RSQLite \
   && rstan \
   && rstatix \
   && rstudioapi \
   && Rttf2pt1 \
   && rversions \
   && rvest \
   && rvg \
   && RWeka \
   && RWekajars \
   && sandwich \
   && sapa \
   && scales \
   && scatterplot3d \
   && seewave \
   && segmented \
   && selectr \
   && SemiPar \
   && seqinr \
   && seriation \
   && servr \
   && sessioninfo \
   && setRNG \
   && sets \
   && sf \
   && sfheaders \
   && sfsmisc \
   && shape \
   && shapefiles \
   && shapes \
   && SHELF \
   && shiny \
   && shinyAce \
   && shinyBS \
   && shinydashboard \
   && shinyFeedback \
   && shinyjqui \
   && shinyjs \
   && shinyMatrix \
   && shinytest \
   && shinythemes \
   && showimage \
   && shrink \
   && signal \
   && SimComp \
   && sirad \
   && sjlabelled \
   && sjmisc \
   && sjPlot \
   && sjstats \
   && slam \
   && slider \
   && smacof \
   && SMPracticals \
   && sn \
   && snakecase \
   && snow \
   && SnowballC \
   && sodium \
   && solrium \
   && sourcetools \
   && sp \
   && spacetime \
   && spam \
   && sparseLDA \
   && SparseM \
   && spatial \
   && spatialwidget \
   && spatstat \
   && spatstat.data \
   && spatstat.utils \
   && spbabel \
   && spData \
   && spdep \
   && spdplyr \
   && spelling \
   && splancs \
   && splus2R \
   && spMaps \
   && SQUAREM \
   && stabledist \
   && StanHeaders \
   && stars \
   && startupmsg \
   && statmod \
   && stdReg \
   && stopwords \
   && storr \
   && stringdist \
   && stringi \
   && stringr \
   && styler \
   && summarytools \
   && SuppDists \
   && survey \
   && survival \
   && sweep \
   && sys \
   && systemfit \
   && systemfonts \
   && taxize \
   && tcltk2 \
   && tensor \
   && tensorA \
   && testthat \
   && texreg \
   && TH.data \
   && tibble \
   && tibbletime \
   && tictoc \
   && tidyr \
   && tidyselect \
   && tidytext \
   && tidyverse \
   && tiff \
   && timeDate \
   && timeSeries \
   && timetk \
   && tinytex \
   && tkrplot \
   && tm \
   && tmap \
   && tmaptools \
   && TMB \
   && todor \
   && tokenizers \
   && translate \
   && treeClust \
   && trend \
   && triangle \
   && triebeard \
   && truncnorm \
   && tseries \
   && TSP \
   && TTR \
   && tuneR \
   && turboEM \
   && tweenr \
   && ucminf \
   && udapi \
   && udunits2 \
   && units \
   && unmarked \
   && urca \
   && urltools \
   && uroot \
   && useful \
   && usethis \
   && utf8 \
   && uuid \
   && V8 \
   && vcd \
   && vcfR \
   && vctrs \
   && vegan \
   && vegan3d \
   && venneuler \
   && versions \
   && VGAM \
   && viridis \
   && viridisLite \
   && visNetwork \
   && warp \
   && waveslim \
   && wavethresh \
   && wbstats \
   && WDI \
   && webdriver \
   && webshot \
   && weights \
   && wellknown \
   && whisker \
   && whoami \
   && WikidataR \
   && WikipediR \
   && wikitaxa \
   && withr \
   && wmtsa \
   && wnominate \
   && wordcloud \
   && worrms \
   && writexl \
   && xfun \
   && XLConnect \
   && xlsx \
   && xlsxjars \
   && XML \
   && xml2 \
   && xopen \
   && xtable \
   && xts \
   && yaImpute \
   && yaml \
   && yesno \
   && zeallot \
   && zip \
   && zoo 